name: Lucky Router CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: "*"

jobs:
  check_format:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:0.35.1

    steps:
      - uses: actions/checkout@v1
      - name: Format
        run: crystal tool format --check

  specs:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:0.35.1

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
